# Generated by Django 4.2.5 on 2023-09-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='order_items', through='inventory.OrderItem', to='inventory.product'),
        ),
    ]
