# Generated by Django 4.2.5 on 2023-09-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='order_items', through='inventory.OrderItem', to='inventory.product'),
        ),
    ]
